### ISSUE TITLE
ImportError: cannot import name 'Layer'

### ISSUE THREAD

**Issue by jeffin07** [cjpurackal/m2det-tf#5]
When i try to run 

`python3 run.py config.json`

it throws an ImportError

`Traceback (most recent call last):
File "run.py", line 4, in <module>
from tensorflow.keras.layers import Conv2D
File "/home/user/.local/lib/python3.6/site-packages/tensorflow/keras/__init__.py", line 20, in <module>
from . import layers
File "/home/user/.local/lib/python3.6/site-packages/tensorflow/keras/layers/__init__.py", line 8, in <module>
from tensorflow.python.estimator.keras import Layer
ImportError: cannot import name 'Layer'`

Tensorflow version : 1.13

**Comment by anandhupvr** [comment]
@jeffin07  It should be tensorflow version issue. My version is 1.12 and it works fine

Try this in you version

`from tensorflow import keras`
`from keras.layers import Conv2D`

**Comment by cjpurackal** [comment]
@jeffin07 Try upgrading tensorflow

**Comment by jeffin07** [comment]
@anandhupvr thanks for the reply  actually i already tried that and it's working. But that makes no sense. Why the other method not working ?

**Comment by anandhupvr** [comment]
@jeffin07  When you upgrade to tensorflow 2.0 it all makes sense


lets hope :wink:

**Comment by jeffin07** [comment]
> @jeffin07 Try upgrading tensorflow

@cjpurackal   upgraded using this 
`pip3 install --upgrade tensorflow-gpu`
but no luck  :disappointed:  
is  there any other way ?

**Comment by cjpurackal** [comment]
Have made some changes with the latest commit. This is supposed to work with tf2.0, not anything less than that. Create a virtualenv for tf2.0 and test it
